name: Pull Request Validation

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  # Job 1: Code Quality Check
  quality-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Check build
        run: npm run build
        env:
          CI: false

      - name: Run security audit
        run: npm audit --audit-level high
        continue-on-error: true

  # Job 2: Validate package.json and dependencies
  validate-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Validate package.json
        run: npm ls --depth=0

      - name: Check for outdated packages
        run: npm outdated || true

      - name: Install and verify dependencies
        run: |
          npm ci
          npm list --production

  # Job 3: Build size analysis
  build-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build
        env:
          CI: false

      - name: Analyze bundle size
        run: |
          echo "Build completed successfully!"
          du -sh dist/
          echo "--- Build Contents ---"
          ls -la dist/
          echo "--- Asset Sizes ---"
          find dist/ -type f -name "*.js" -o -name "*.css" -o -name "*.html" | xargs ls -lh

      - name: Comment PR with build info
        uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        with:
          script: |
            const fs = require('fs');
            const path = require('path');

            // Get build size
            const { execSync } = require('child_process');
            const buildSize = execSync('du -sh dist/').toString().split('\t')[0];

            const comment = `## 🚀 Build Analysis

            ✅ Build completed successfully!
            📦 Total build size: **${buildSize.trim()}**

            The application has been built and is ready for deployment.`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
